/**
 * Define all the constants required in application inside this file and export them
 */
export const FETCHING_PEOPLE = 'FETCHING_PEOPLE';
export const FETCHING_PEOPLE_SUCCESS = 'FETCHING_PEOPLE_SUCCESS';

export const FETCHING_POST = 'FETCHING_POST';
export const FETCHING_POST_SUCCESS = 'FETCHING_POST_SUCCESS';
export const FETCHING_POST_END = 'FETCHING_POST_END';

export const UPDATING_POST = 'UPDATING_POST';
export const UPDATING_POST_SUCCESS = 'UPDATING_POST_SUCCESS';
export const POST_EDIT_BEGIN = 'POST_EDIT_BEGIN'
export const POST_EDIT_END = 'POST_EDIT_END';

export const GET_POST = 'GET_POST';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const FAILURE = 'FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const DELETING_POST_SUCCESS = 'DELETING_POST_SUCCESS';
export const DELETE_START = 'DELETE_START';
export const DELETE_END = 'DELETE_END';

export const ADDING_POST_START = 'ADDING_POST_START';
export const ADDING_POST_END = 'ADDING_POST_END';

export const FETCHING_IMAGES_SUCCESS = 'FETCHING_IMAGES_SUCCESS';
export const FETCHING_IMAGES_END = 'FETCHING_IMAGES_END';
export const FETCHING_IMAGES_FAILURE = 'FETCHING_IMAGES_FAILURE';
export const GET_IMAGES = 'GET_IMAGES';

export const FETCHING_PAGES_SUCCESS = 'FETCHING_PAGES_SUCCESS';
export const FETCHING_PAGES_END = 'FETCHING_PAGES_END';
export const FETCHING_PAGES_FAILURE = 'FETCHING_PAGES_FAILURE';
export const GET_PAGES = 'GET_PAGES';